[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://challenges.cloudflare.com; frame-src 'self' https://challenges.cloudflare.com https://*.turnstile.com; connect-src 'self' https://challenges.cloudflare.com https://*.turnstile.com;"